name: workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.8.0
  - gensim=3.8.0
  - jupyterlab=1.1.4
  - lxml=4.4.1
  - nltk=3.4.5
  - nodejs=10.13.0
  - pandas=0.25.1
  - pandas-datareader>=0.8.0
  - pip=19.2.2
  - plotly=4.1.1
  - pyarrow=0.13.0
  - python=3.7
  - requests=2.22.0
  - scikit-learn=0.21.3
  - spacy=2.1.8
  - textblob=0.15.3
  - pip:
    - nytimesarticle==0.1.0
    - tensorflow==2.0.0rc2
